"""
Blender script: import an FBX file, find the mesh with shape keys,
write basis + each non-basis shape key as an OBJ file in `out_dir`.

Coordinate frame: we write everything in **Y-up / forward -Z** (the OBJ /
three.js convention). The pipeline does this in two steps for every vertex:

  1. `matrix_world @ co` → bake the FBX importer's axis-conversion rotation
     into the coords. After this, vertices are in Blender's scene frame
     (Z-up / forward -Y).
  2. `(x, z, -y)` → rotate -90° around X to get Y-up.

Why both steps:
  - Step 1 alone (the previous version) left the OBJ in Blender's Z-up
    frame. Three.js (Y-up) renders that with the head facing the camera
    instead of upright.
  - Skipping step 1 (writing `d.co` directly) sometimes worked, sometimes
    didn't — it depends on whether the FBX file was authored as Y-up or
    Z-up internally. With matrix_world we get a single known frame
    regardless of the source.

Same transform is applied to basis AND every shape key, so the deformation
transfer step sees a consistent frame between the source rest pose and
each source deformation — which it requires for the per-triangle gradient
to make sense.

We don't use the depsgraph evaluator: shape-key data blocks already store
the absolute (local) vertex positions for that key, which we read directly
via `key_block.data[i].co`.

Invocation (Blender 4.x / 5.x):
  blender --background --python extract_shape_keys.py -- <fbx_path> <out_dir>

The script prints a single `DT_RESULT:<json>` line at the end with the
manifest, which the host process parses.
"""
import json
import os
import re
import sys

import bpy  # type: ignore


def fail(msg: str) -> None:
    print("DT_RESULT:" + json.dumps({"ok": False, "error": msg}), flush=True)
    sys.exit(1)


def sanitize(name: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]", "_", name)
    return safe[:80] if safe else "shape_key"


def main() -> None:
    if "--" not in sys.argv:
        fail("missing '--' separator before script args")
    args = sys.argv[sys.argv.index("--") + 1:]
    if len(args) < 2:
        fail(f"need <fbx_path> <out_dir>, got {args}")
    fbx_path, out_dir = args[0], args[1]

    if not os.path.isfile(fbx_path):
        fail(f"FBX not found: {fbx_path}")
    os.makedirs(out_dir, exist_ok=True)

    # Clean slate
    bpy.ops.wm.read_factory_settings(use_empty=True)

    # Import FBX
    try:
        bpy.ops.import_scene.fbx(filepath=fbx_path)
    except Exception as e:  # noqa: BLE001
        fail(f"FBX import failed: {e}")

    # Pick first mesh that has shape keys; fall back to first mesh
    target_obj = None
    for obj in bpy.data.objects:
        if obj.type != "MESH":
            continue
        if obj.data.shape_keys is not None and len(obj.data.shape_keys.key_blocks) > 0:
            target_obj = obj
            break
    if target_obj is None:
        for obj in bpy.data.objects:
            if obj.type == "MESH":
                target_obj = obj
                break
    if target_obj is None:
        fail("FBX contains no mesh")

    mesh = target_obj.data
    mw = target_obj.matrix_world
    polys = list(mesh.polygons)
    n_verts = len(mesh.vertices)

    def to_y_up(co_vec):
        """Apply matrix_world (FBX→Blender axis fix), then convert Z-up→Y-up.

        Result is in the OBJ / three.js convention (Y-up, forward -Z) which
        keeps the viewport upright and lets DT compute gradients in a frame
        consistent with the user-uploaded target OBJ.
        """
        wx, wy, wz = mw @ co_vec  # bake importer's axis-conversion rotation
        return (wx, wz, -wy)      # Z-up -> Y-up: rotate -90° around X

    def write_obj_from_key(key_block, out_path: str) -> int:
        """Write OBJ from a shape key's absolute vertex positions, Y-up."""
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("# Generated by Chameleon Warp fbx_io (Y-up)\n")
            for d in key_block.data:
                x, y, z = to_y_up(d.co)
                f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
            for poly in polys:
                vs = list(poly.vertices)
                # Fan-triangulate quads / n-gons
                for i in range(1, len(vs) - 1):
                    f.write(f"f {vs[0]+1} {vs[i]+1} {vs[i+1]+1}\n")
        return os.path.getsize(out_path)

    # Manually evaluate as a fallback when there are no shape keys at all
    def write_obj_from_basis_mesh(out_path: str) -> int:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("# Generated by Chameleon Warp fbx_io (Y-up)\n")
            for v in mesh.vertices:
                x, y, z = to_y_up(v.co)
                f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
            for poly in polys:
                vs = list(poly.vertices)
                for i in range(1, len(vs) - 1):
                    f.write(f"f {vs[0]+1} {vs[i]+1} {vs[i+1]+1}\n")
        return os.path.getsize(out_path)

    sk = mesh.shape_keys

    basis_path = os.path.join(out_dir, "basis.obj")
    if sk is not None:
        write_obj_from_key(sk.reference_key, basis_path)
    else:
        write_obj_from_basis_mesh(basis_path)

    poses = []
    seen_basenames = {"basis"}
    if sk is not None:
        basis_name = sk.reference_key.name
        for key in sk.key_blocks:
            if key.name == basis_name:
                continue
            safe = sanitize(key.name)
            base = safe
            i = 1
            while base in seen_basenames:
                base = f"{safe}_{i}"
                i += 1
            seen_basenames.add(base)
            path = os.path.join(out_dir, f"{base}.obj")
            size = write_obj_from_key(key, path)
            poses.append({"name": key.name, "filename": f"{base}.obj", "path": path, "size": size})

    manifest = {
        "ok": True,
        "mesh_name": target_obj.name,
        "vertex_count": n_verts,
        "polygon_count": len(polys),
        "basis_path": basis_path,
        "poses": poses,
    }
    print("DT_RESULT:" + json.dumps(manifest), flush=True)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:  # noqa: BLE001
        import traceback
        traceback.print_exc()
        fail(f"unexpected error: {e}")
